export type FlowDiagramId = 'inference' | 'onprem' | 'payment' | 'van' | 'point' | 'kiosk' | 'stock' | 'spire';

export interface PipelineNodeSeed {
  id: string;
  label: string;
  caption: string;
  x: number;
  y: number;
  tone?: 'ember' | 'mute' | 'danger' | 'ok';
  kicker?: string;
}

export interface PipelineEdgeSeed {
  id: string;
  source: string;
  target: string;
  label?: string;
  animated?: boolean;
  kind?: 'flow' | 'fail' | 'retry';
}

export interface PipelineGroupSeed {
  id: string;
  label: string;
  caption?: string;
  nodeIds: string[];
}

export interface PipelineDiagram {
  id: FlowDiagramId;
  title: string;
  subtitle: string;
  projectId?: string;
  groups: PipelineGroupSeed[];
  nodes: PipelineNodeSeed[];
  edges: PipelineEdgeSeed[];
}

export const PIPELINE_DIAGRAMS: PipelineDiagram[] = [
  {
    id: 'inference',
    title: '문서 추론 아키텍처',
    subtitle: '출처는 어댑터로 흡수하고, 실패는 상태로 남겨 지점부터 다시 넣습니다.',
    projectId: 'lomin-backend',
    groups: [
      { id: 'inf-g-in', label: '입수', caption: '출처별 경로', nodeIds: ['inf-nas', 'inf-s3', 'inf-api'] },
      { id: 'inf-g-ad', label: '흡수', caption: '본체와 분리', nodeIds: ['inf-adapter'] },
      { id: 'inf-g-inf', label: '가드 · 추론', caption: 'Python 레이어', nodeIds: ['inf-fastfail', 'inf-fastapi'] },
      { id: 'inf-g-or', label: '오케스트레이션', caption: '상태 · 계약', nodeIds: ['inf-spring', 'inf-redis'] },
      { id: 'inf-g-w', label: '분산 · 재처리', caption: 'GPU 워커', nodeIds: ['inf-workers', 'inf-retry'] },
      { id: 'inf-g-st', label: '적재', caption: '결과 저장', nodeIds: ['inf-minio', 'inf-rdb'] },
    ],
    nodes: [
      { id: 'inf-nas', label: 'NAS', caption: '온프레미스 반입', x: 0, y: 40, tone: 'mute', kicker: 'On-prem' },
      { id: 'inf-s3', label: 'S3', caption: '클라우드 반입', x: 0, y: 160, tone: 'mute', kicker: 'Cloud' },
      { id: 'inf-api', label: 'API', caption: '실시간 반입', x: 0, y: 280, tone: 'mute', kicker: 'Online' },
      {
        id: 'inf-adapter',
        label: 'Ingest Adapter',
        caption: '출처 매핑만 담당. 솔루션 본체는 고객 인프라에 맞추지 않음',
        x: 260,
        y: 160,
        tone: 'ember',
        kicker: '경계',
      },
      {
        id: 'inf-fastfail',
        label: 'Fast Fail',
        caption: '암호·손상 PDF는 렌더 전에 원인을 상태에 남김',
        x: 520,
        y: 40,
        tone: 'danger',
        kicker: '차단',
      },
      {
        id: 'inf-fastapi',
        label: 'FastAPI',
        caption: '렌더·추론에 가까운 Python 레이어',
        x: 520,
        y: 200,
        tone: 'ember',
        kicker: 'Infer',
      },
      {
        id: 'inf-spring',
        label: 'Spring Kotlin',
        caption: '상태머신 · 연동 계약. 깨지면 재처리 입구가 사라지는 구간',
        x: 780,
        y: 120,
        tone: 'ember',
        kicker: 'State',
      },
      {
        id: 'inf-redis',
        label: 'Redis',
        caption: '진행 상태. 실패 지점을 서버에 남김',
        x: 780,
        y: 280,
        tone: 'mute',
        kicker: '상태',
      },
      {
        id: 'inf-workers',
        label: 'GPU Workers',
        caption: '단일 대기열을 워커로 나눠 일 8만 건 병렬 추론',
        x: 1040,
        y: 60,
        tone: 'ok',
        kicker: 'Compute',
      },
      {
        id: 'inf-retry',
        label: 'Recovery',
        caption: '스토리지 순간 장애 등 복구 가능 건을 지점부터 재투입',
        x: 1040,
        y: 240,
        tone: 'ok',
        kicker: '재처리',
      },
      { id: 'inf-minio', label: 'MinIO', caption: '렌더·결과 오브젝트', x: 1300, y: 60, tone: 'mute', kicker: 'Object' },
      { id: 'inf-rdb', label: 'RDB', caption: '상태 · 결과 메타', x: 1300, y: 220, tone: 'mute', kicker: 'Meta' },
    ],
    edges: [
      { id: 'e-nas', source: 'inf-nas', target: 'inf-adapter' },
      { id: 'e-s3', source: 'inf-s3', target: 'inf-adapter' },
      { id: 'e-api', source: 'inf-api', target: 'inf-adapter' },
      { id: 'e-ff', source: 'inf-adapter', target: 'inf-fastfail', label: '손상 문서', kind: 'fail' },
      { id: 'e-inf', source: 'inf-adapter', target: 'inf-fastapi', animated: true },
      { id: 'e-kt', source: 'inf-fastapi', target: 'inf-spring', animated: true },
      { id: 'e-st', source: 'inf-spring', target: 'inf-redis', label: '상태 기록' },
      { id: 'e-wk', source: 'inf-spring', target: 'inf-workers', label: '분산', animated: true },
      { id: 'e-rt', source: 'inf-spring', target: 'inf-retry', label: '재처리', kind: 'retry' },
      { id: 'e-re', source: 'inf-retry', target: 'inf-workers', label: '지점 재투입', kind: 'retry' },
      { id: 'e-out-m', source: 'inf-workers', target: 'inf-minio', animated: true },
      { id: 'e-out-r', source: 'inf-workers', target: 'inf-rdb', animated: true },
      { id: 'e-retry-rdb', source: 'inf-retry', target: 'inf-rdb', kind: 'retry' },
    ],
  },
  {
    id: 'onprem',
    title: '온프레미스 구성 아키텍처',
    subtitle: '흩어진 버전 기록을 묶고, 납품 환경을 조합 선택으로 재현합니다.',
    projectId: 'onprem',
    groups: [
      { id: 'op-g-src', label: '파편', caption: '사람이 관리하던 기록', nodeIds: ['op-slack', 'op-conf', 'op-sp'] },
      { id: 'op-g-plat', label: '플랫폼', caption: '구성의 단일 입구', nodeIds: ['op-platform'] },
      { id: 'op-g-art', label: '산출물', caption: '이미지 · 이력 · CLI', nodeIds: ['op-registry', 'op-git', 'op-cli'] },
      { id: 'op-g-ver', label: '버전 묶음', caption: '솔루션 + OSS', nodeIds: ['op-svc', 'op-oss'] },
      { id: 'op-g-site', label: '납품', caption: '고객사 단위', nodeIds: ['op-site'] },
    ],
    nodes: [
      { id: 'op-slack', label: 'Slack', caption: '대화에 남은 버전', x: 0, y: 20, tone: 'mute' },
      { id: 'op-conf', label: 'Confluence', caption: '문서에 남은 설정', x: 0, y: 150, tone: 'mute' },
      { id: 'op-sp', label: 'SharePoint', caption: '파일에 남은 조합', x: 0, y: 280, tone: 'mute' },
      {
        id: 'op-platform',
        label: 'Ops Platform',
        caption: '환경 구성을 전산화. 백엔드 2인 설계',
        x: 280,
        y: 150,
        tone: 'ember',
        kicker: 'Core',
      },
      {
        id: 'op-registry',
        label: 'Image Registry',
        caption: 'Pipeline · Triton · Core 등 서비스 이미지',
        x: 560,
        y: 20,
        tone: 'ok',
        kicker: '이미지',
      },
      { id: 'op-git', label: 'Git', caption: '구성 이력 · 고객사별 추적', x: 560, y: 150, tone: 'ok', kicker: '이력' },
      { id: 'op-cli', label: 'Lomin CLI', caption: '현장 구성 진입점', x: 560, y: 280, tone: 'ok', kicker: '현장' },
      {
        id: 'op-svc',
        label: 'Service Bundle',
        caption: 'Pipeline, Triton, Model Factory, Wrapper',
        x: 860,
        y: 60,
        tone: 'ember',
        kicker: '솔루션',
      },
      {
        id: 'op-oss',
        label: 'OSS Bundle',
        caption: 'DB · Storage · NoSQL 버전을 솔루션과 분리',
        x: 860,
        y: 220,
        tone: 'ember',
        kicker: 'OSS',
      },
      {
        id: 'op-site',
        label: 'Customer Site',
        caption: '고객사 단위 조합으로 납품 환경을 재현',
        x: 1160,
        y: 140,
        tone: 'mute',
        kicker: '100+',
      },
    ],
    edges: [
      { id: 'e-slack', source: 'op-slack', target: 'op-platform' },
      { id: 'e-conf', source: 'op-conf', target: 'op-platform' },
      { id: 'e-sp', source: 'op-sp', target: 'op-platform' },
      { id: 'e-reg', source: 'op-platform', target: 'op-registry', animated: true },
      { id: 'e-git', source: 'op-platform', target: 'op-git' },
      { id: 'e-cli', source: 'op-platform', target: 'op-cli' },
      { id: 'e-svc', source: 'op-registry', target: 'op-svc', animated: true },
      { id: 'e-oss', source: 'op-git', target: 'op-oss' },
      { id: 'e-cli-site', source: 'op-cli', target: 'op-site', label: '현장 적용' },
      { id: 'e-svc-site', source: 'op-svc', target: 'op-site', animated: true },
      { id: 'e-oss-site', source: 'op-oss', target: 'op-site' },
    ],
  },
  {
    id: 'payment',
    title: '결제 적재 아키텍처',
    subtitle: '전송과 저장을 나누고, 끊겨도 로컬에 들고 있다가 다시 밀어 넣습니다.',
    projectId: 'payment',
    groups: [
      { id: 'pay-g-edge', label: '현장', caption: '단말 · 단절 대비', nodeIds: ['pay-kiosk'] },
      { id: 'pay-g-q', label: '전송', caption: '비동기 경계', nodeIds: ['pay-local', 'pay-sqs'] },
      { id: 'pay-g-w', label: '처리', caption: '서버사이드', nodeIds: ['pay-dlq', 'pay-worker'] },
      { id: 'pay-g-st', label: '적재 · 관찰', caption: '일 40만 건', nodeIds: ['pay-monitor', 'pay-rdb'] },
    ],
    nodes: [
      {
        id: 'pay-kiosk',
        label: 'KIOSK',
        caption: '현장 단말. 예전엔 1분마다 미전송 분을 Push',
        x: 40,
        y: 160,
        tone: 'mute',
        kicker: 'Edge',
      },
      {
        id: 'pay-local',
        label: 'Local Buffer',
        caption: '네트워크가 끊겨도 로컬에 들고 복구 후 재전송',
        x: 320,
        y: 40,
        tone: 'ok',
        kicker: '유실 방지',
      },
      {
        id: 'pay-sqs',
        label: 'SQS',
        caption: '전송과 DB 저장을 분리한 비동기 적재',
        x: 320,
        y: 200,
        tone: 'ember',
        kicker: 'Queue',
      },
      {
        id: 'pay-dlq',
        label: 'DLQ',
        caption: '실패한 적재를 가시화. 유실 경로를 닫음',
        x: 600,
        y: 40,
        tone: 'danger',
        kicker: '실패',
      },
      {
        id: 'pay-worker',
        label: 'Worker',
        caption: '서버사이드 단독 구현. 멱등 저장',
        x: 600,
        y: 200,
        tone: 'ember',
        kicker: 'Worker',
      },
      {
        id: 'pay-monitor',
        label: 'Monitor',
        caption: '성공률 · 큐/DLQ 적재량 · 워커 상태',
        x: 880,
        y: 40,
        tone: 'ok',
        kicker: '관찰',
      },
      { id: 'pay-rdb', label: 'RDB', caption: '피크 일 40만 건까지 적재', x: 880, y: 200, tone: 'mute', kicker: 'Store' },
    ],
    edges: [
      { id: 'e-kiosk-local', source: 'pay-kiosk', target: 'pay-local', label: '단절 시', kind: 'retry' },
      { id: 'e-kiosk-sqs', source: 'pay-kiosk', target: 'pay-sqs', animated: true },
      { id: 'e-local-sqs', source: 'pay-local', target: 'pay-sqs', label: '복구 후', kind: 'retry' },
      { id: 'e-sqs-worker', source: 'pay-sqs', target: 'pay-worker', animated: true },
      { id: 'e-sqs-dlq', source: 'pay-sqs', target: 'pay-dlq', kind: 'fail' },
      { id: 'e-worker-rdb', source: 'pay-worker', target: 'pay-rdb', animated: true },
      { id: 'e-worker-mon', source: 'pay-worker', target: 'pay-monitor' },
      { id: 'e-dlq-mon', source: 'pay-dlq', target: 'pay-monitor', kind: 'fail' },
    ],
  },
  {
    id: 'kiosk',
    title: '다중 브랜드 KIOSK 아키텍처',
    subtitle: '브랜드별 DB·API 차이를 설정으로 흡수하고, 공통 런타임 하나로 배포합니다.',
    projectId: 'kiosk-multi',
    groups: [
      { id: 'kio-g-br', label: '브랜드', caption: '제각각인 저장·API', nodeIds: ['kio-a', 'kio-b', 'kio-c'] },
      { id: 'kio-g-core', label: '공통 설계', caption: '마스터 기준', nodeIds: ['kio-master'] },
      { id: 'kio-g-cfg', label: '설정', caption: '브랜드 전용이 아니면', nodeIds: ['kio-config', 'kio-common'] },
      { id: 'kio-g-run', label: '런타임', caption: '단일 코드베이스', nodeIds: ['kio-runtime', 'kio-legacy'] },
    ],
    nodes: [
      { id: 'kio-a', label: 'Brand A', caption: 'DB·API가 달라도 역할은 같음', x: 0, y: 20, tone: 'mute' },
      { id: 'kio-b', label: 'Brand B', caption: '개별 프로젝트로 반복 배포되던 구조', x: 0, y: 150, tone: 'mute' },
      { id: 'kio-c', label: 'Brand C', caption: '기존 고객사 KIOSK', x: 0, y: 280, tone: 'mute' },
      {
        id: 'kio-master',
        label: 'Master Server',
        caption: '중앙 기준으로 공통 설계를 다시 잡음',
        x: 280,
        y: 150,
        tone: 'ember',
        kicker: 'Core',
      },
      {
        id: 'kio-config',
        label: 'Env Config',
        caption: '브랜드 전용 요구가 아니면 환경설정으로 전환',
        x: 560,
        y: 60,
        tone: 'ok',
        kicker: '설정',
      },
      {
        id: 'kio-common',
        label: 'Common Modules',
        caption: '주문 · 결제 · 메뉴 등 공통 역할',
        x: 560,
        y: 220,
        tone: 'ok',
        kicker: '공통',
      },
      {
        id: 'kio-runtime',
        label: 'Multi-brand KIOSK',
        caption: '신규 도입과 기존 흡수가 설정으로 됨',
        x: 840,
        y: 90,
        tone: 'ember',
        kicker: '배포',
      },
      {
        id: 'kio-legacy',
        label: 'Legacy KIOSK',
        caption: '고객사별로 나가 있던 개별 코드를 다시 넣음',
        x: 840,
        y: 250,
        tone: 'danger',
        kicker: '흡수',
      },
    ],
    edges: [
      { id: 'e-a', source: 'kio-a', target: 'kio-master' },
      { id: 'e-b', source: 'kio-b', target: 'kio-master' },
      { id: 'e-c', source: 'kio-c', target: 'kio-master' },
      { id: 'e-cfg', source: 'kio-master', target: 'kio-config', animated: true },
      { id: 'e-com', source: 'kio-master', target: 'kio-common', animated: true },
      { id: 'e-run', source: 'kio-config', target: 'kio-runtime', animated: true },
      { id: 'e-run2', source: 'kio-common', target: 'kio-runtime', animated: true },
      { id: 'e-leg', source: 'kio-legacy', target: 'kio-runtime', label: '흡수', kind: 'retry' },
    ],
  },
  {
    id: 'van',
    title: 'VAN 전환 아키텍처',
    subtitle: '결제·환불·조회는 공통으로 두고, 계약 VAN만 설정으로 갈아끼웁니다.',
    projectId: 'van-switch',
    groups: [
      { id: 'van-g-edge', label: '단말', caption: '현장 결제', nodeIds: ['van-kiosk'] },
      { id: 'van-g-api', label: '공통 동작', caption: '계약과 분리', nodeIds: ['van-api'] },
      { id: 'van-g-sw', label: '전환', caption: '설정 · 전략', nodeIds: ['van-config', 'van-factory'] },
      { id: 'van-g-van', label: '구현체', caption: '4사 · 페이', nodeIds: ['van-a', 'van-b', 'van-c', 'van-d'] },
      { id: 'van-g-io', label: '연동', caption: '피크 · 유실', nodeIds: ['van-async', 'van-rdb'] },
    ],
    nodes: [
      {
        id: 'van-kiosk',
        label: 'KIOSK',
        caption: '같은 결제 흐름을 브랜드와 무관하게 호출',
        x: 0,
        y: 140,
        tone: 'mute',
        kicker: 'Edge',
      },
      {
        id: 'van-api',
        label: 'Payment API',
        caption: '결제 · 환불 · 조회를 공통 동작으로 고정',
        x: 260,
        y: 140,
        tone: 'ember',
        kicker: '계약',
      },
      {
        id: 'van-config',
        label: 'Env Config',
        caption: '페이 포함 결제수단을 설정만으로 전환',
        x: 540,
        y: 40,
        tone: 'ok',
        kicker: '설정',
      },
      {
        id: 'van-factory',
        label: 'Factory · Strategy',
        caption: 'VAN 구현체만 교체. 공통 동작은 그대로',
        x: 540,
        y: 220,
        tone: 'ember',
        kicker: '전환',
      },
      { id: 'van-a', label: 'VAN A', caption: '기존 1개사 계약', x: 820, y: 20, tone: 'mute' },
      { id: 'van-b', label: 'VAN B', caption: '확장 계약', x: 820, y: 120, tone: 'mute' },
      { id: 'van-c', label: 'VAN C', caption: '확장 계약', x: 820, y: 220, tone: 'mute' },
      { id: 'van-d', label: 'VAN D · Pay', caption: '페이 포함 4사', x: 820, y: 320, tone: 'mute' },
      {
        id: 'van-async',
        label: 'Async VAN I/O',
        caption: '피크타임 부하와 유실을 막기 위해 연동을 비동기로',
        x: 1100,
        y: 80,
        tone: 'ok',
        kicker: '비동기',
      },
      { id: 'van-rdb', label: 'RDB', caption: '승인 · 환불 결과', x: 1100, y: 240, tone: 'mute', kicker: 'Store' },
    ],
    edges: [
      { id: 'e-van-kiosk', source: 'van-kiosk', target: 'van-api', animated: true },
      { id: 'e-van-cfg', source: 'van-api', target: 'van-config' },
      { id: 'e-van-fac', source: 'van-api', target: 'van-factory', animated: true },
      { id: 'e-van-cfg-fac', source: 'van-config', target: 'van-factory', label: '선택' },
      { id: 'e-van-a', source: 'van-factory', target: 'van-a' },
      { id: 'e-van-b', source: 'van-factory', target: 'van-b' },
      { id: 'e-van-c', source: 'van-factory', target: 'van-c' },
      { id: 'e-van-d', source: 'van-factory', target: 'van-d' },
      { id: 'e-van-a-io', source: 'van-a', target: 'van-async' },
      { id: 'e-van-b-io', source: 'van-b', target: 'van-async' },
      { id: 'e-van-c-io', source: 'van-c', target: 'van-async' },
      { id: 'e-van-d-io', source: 'van-d', target: 'van-async' },
      { id: 'e-van-store', source: 'van-async', target: 'van-rdb', animated: true },
    ],
  },
  {
    id: 'point',
    title: '자사 포인트 아키텍처',
    subtitle: '외부 수수료 경로를 끊고, 적립·사용의 잔액을 트랜잭션과 멱등으로 맞춥니다.',
    projectId: 'inhouse-point',
    groups: [
      { id: 'pt-g-edge', label: '단말', caption: '적립 · 사용 요청', nodeIds: ['pt-kiosk'] },
      { id: 'pt-g-old', label: '대체', caption: '수수료 경로', nodeIds: ['pt-ext'] },
      { id: 'pt-g-api', label: '자사 포인트', caption: '적립 · 사용', nodeIds: ['pt-api'] },
      { id: 'pt-g-guard', label: '정합성', caption: '멱등 · 트랜잭션', nodeIds: ['pt-idem', 'pt-tx'] },
      { id: 'pt-g-st', label: '잔액', caption: '성능보다 맞춤', nodeIds: ['pt-bal'] },
    ],
    nodes: [
      {
        id: 'pt-kiosk',
        label: 'KIOSK',
        caption: '주문 흐름에서 적립·사용을 요청',
        x: 0,
        y: 140,
        tone: 'mute',
        kicker: 'Edge',
      },
      {
        id: 'pt-ext',
        label: 'External Point',
        caption: '외부 연동 수수료가 나던 경로',
        x: 260,
        y: 40,
        tone: 'danger',
        kicker: '수수료',
      },
      {
        id: 'pt-api',
        label: 'Point API',
        caption: '자사 적립·사용. 개발 리드 설계 아래 구현',
        x: 540,
        y: 140,
        tone: 'ember',
        kicker: 'Core',
      },
      {
        id: 'pt-idem',
        label: 'Idempotency',
        caption: '같은 사용·적립 요청을 두 번 쓰지 않음',
        x: 820,
        y: 40,
        tone: 'ok',
        kicker: '멱등',
      },
      {
        id: 'pt-tx',
        label: 'Transaction',
        caption: '잔액 변경을 한 단위로 묶어 맞춤',
        x: 820,
        y: 220,
        tone: 'ok',
        kicker: '트랜잭션',
      },
      {
        id: 'pt-bal',
        label: 'Balance Store',
        caption: '잔액 정합성을 성능보다 우선',
        x: 1100,
        y: 140,
        tone: 'mute',
        kicker: 'Store',
      },
    ],
    edges: [
      { id: 'e-pt-old', source: 'pt-kiosk', target: 'pt-ext', kind: 'fail', label: '이전' },
      { id: 'e-pt-req', source: 'pt-kiosk', target: 'pt-api', animated: true },
      { id: 'e-pt-cut', source: 'pt-ext', target: 'pt-api', kind: 'retry', label: '대체' },
      { id: 'e-pt-idem', source: 'pt-api', target: 'pt-idem', animated: true },
      { id: 'e-pt-tx', source: 'pt-api', target: 'pt-tx', animated: true },
      { id: 'e-pt-idem-tx', source: 'pt-idem', target: 'pt-tx', label: '가드' },
      { id: 'e-pt-bal-i', source: 'pt-idem', target: 'pt-bal', animated: true },
      { id: 'e-pt-bal', source: 'pt-tx', target: 'pt-bal', animated: true },
    ],
  },
  {
    id: 'stock',
    title: 'Stock Agent 아키텍처',
    subtitle: '시계열을 한 스키마로 모으고, 자연어를 정량 쿼리로 바꿔 근거 있는 답을 냅니다.',
    projectId: 'stock-agent',
    groups: [
      { id: 'st-g-data', label: '데이터', caption: '최근 3개년', nodeIds: ['st-ohlcv', 'st-meta'] },
      { id: 'st-g-sch', label: '정규화', caption: '단일 스키마', nodeIds: ['st-schema'] },
      { id: 'st-g-q', label: '질의', caption: '자연어 → 정량', nodeIds: ['st-nl', 'st-parser'] },
      { id: 'st-g-ag', label: '에이전트', caption: 'RAG · LLM', nodeIds: ['st-rag', 'st-llm'] },
      { id: 'st-g-out', label: '응답', caption: '근거와 수치', nodeIds: ['st-out'] },
    ],
    nodes: [
      { id: 'st-ohlcv', label: 'OHLCV', caption: '일·분 시계열', x: 0, y: 50, tone: 'mute', kicker: '시세' },
      { id: 'st-meta', label: '종목 메타', caption: '종목 · 시장 정보', x: 0, y: 200, tone: 'mute', kicker: '메타' },
      {
        id: 'st-schema',
        label: 'Unified Schema',
        caption: '정제·정규화한 분석용 단일 스키마',
        x: 260,
        y: 120,
        tone: 'ember',
        kicker: 'Store',
      },
      {
        id: 'st-nl',
        label: 'Natural Language',
        caption: '삼성전자 2024년 거래량 급등일 알려줘',
        x: 520,
        y: 40,
        tone: 'mute',
        kicker: '입력',
      },
      {
        id: 'st-parser',
        label: 'Query Parser',
        caption: '종목 · 기간 · 지표를 정량 쿼리로 변환',
        x: 520,
        y: 200,
        tone: 'ember',
        kicker: '해석',
      },
      { id: 'st-rag', label: 'RAG', caption: '스키마에서 근거 구간을 회수', x: 780, y: 60, tone: 'ok', kicker: '검색' },
      {
        id: 'st-llm',
        label: 'LLM Agent',
        caption: '수치와 근거를 묶어 답변',
        x: 780,
        y: 220,
        tone: 'ember',
        kicker: '생성',
      },
      {
        id: 'st-out',
        label: 'Grounded Answer',
        caption: '수익률 · 낙폭 등 수치로 응답',
        x: 1040,
        y: 120,
        tone: 'ok',
        kicker: '출력',
      },
    ],
    edges: [
      { id: 'e-oh', source: 'st-ohlcv', target: 'st-schema' },
      { id: 'e-meta', source: 'st-meta', target: 'st-schema' },
      { id: 'e-nl', source: 'st-nl', target: 'st-parser', animated: true },
      { id: 'e-sch-p', source: 'st-schema', target: 'st-parser' },
      { id: 'e-p-rag', source: 'st-parser', target: 'st-rag', animated: true },
      { id: 'e-sch-rag', source: 'st-schema', target: 'st-rag' },
      { id: 'e-rag-llm', source: 'st-rag', target: 'st-llm', animated: true },
      { id: 'e-p-llm', source: 'st-parser', target: 'st-llm' },
      { id: 'e-out', source: 'st-llm', target: 'st-out', animated: true },
    ],
  },
  {
    id: 'spire',
    title: 'Spire 분석 아키텍처',
    subtitle: '플레이 로그를 걸러 전투 시점으로 재현하고, 기대 피해로 카드 가치를 확인합니다.',
    projectId: 'spire',
    groups: [
      { id: 'sp-g-in', label: '수집', caption: '공개 런 로그', nodeIds: ['sp-runs'] },
      { id: 'sp-g-st', label: '적재', caption: '컬럼형 저장', nodeIds: ['sp-parquet'] },
      { id: 'sp-g-f', label: '정제', caption: '코호트 · 손상 런', nodeIds: ['sp-filter', 'sp-drop'] },
      { id: 'sp-g-sim', label: '재현', caption: '층별 상태', nodeIds: ['sp-sim', 'sp-battle'] },
      { id: 'sp-g-ml', label: '학습 · 인사이트', caption: '기대 피해', nodeIds: ['sp-model', 'sp-insight'] },
    ],
    nodes: [
      {
        id: 'sp-runs',
        label: 'Run Logs',
        caption: '약 3,200만 건 플레이 로그',
        x: 0,
        y: 140,
        tone: 'mute',
        kicker: 'Raw',
      },
      {
        id: 'sp-parquet',
        label: 'Parquet',
        caption: '런 단위 컬럼 저장. 병렬 읽기',
        x: 260,
        y: 140,
        tone: 'ember',
        kicker: 'Store',
      },
      {
        id: 'sp-filter',
        label: 'Cohort Filter',
        caption: '4캐릭터 · 승천 0–20 · 베타/무한 제외',
        x: 540,
        y: 40,
        tone: 'ok',
        kicker: '정제',
      },
      {
        id: 'sp-drop',
        label: 'Run Guard',
        caption: '필드 누락 · HP 불일치 런은 재현 전에 제외',
        x: 540,
        y: 240,
        tone: 'danger',
        kicker: '가드',
      },
      {
        id: 'sp-sim',
        label: 'Floor Simulator',
        caption: '카드 선택 · 유물 · 이벤트로 층마다 덱을 재구성',
        x: 840,
        y: 40,
        tone: 'ember',
        kicker: '재현',
      },
      {
        id: 'sp-battle',
        label: 'Battle Snapshot',
        caption: '전투 시점의 덱 · 유물 · 적 · 피해',
        x: 840,
        y: 240,
        tone: 'ok',
        kicker: '전투',
      },
      {
        id: 'sp-model',
        label: 'Damage Model',
        caption: '덱 · 유물 · 적 타입으로 기대 피해를 학습',
        x: 1140,
        y: 40,
        tone: 'ember',
        kicker: '학습',
      },
      {
        id: 'sp-insight',
        label: 'Card Value',
        caption: "2.2 패치 사일런트 기준 '곡예'가 가장 가치 높음",
        x: 1140,
        y: 240,
        tone: 'ok',
        kicker: '인사이트',
      },
    ],
    edges: [
      { id: 'e-sp-runs', source: 'sp-runs', target: 'sp-parquet', animated: true },
      { id: 'e-sp-f', source: 'sp-parquet', target: 'sp-filter', animated: true },
      { id: 'e-sp-drop', source: 'sp-parquet', target: 'sp-drop', kind: 'fail', label: '손상 런' },
      { id: 'e-sp-sim', source: 'sp-filter', target: 'sp-sim', animated: true },
      { id: 'e-sp-battle', source: 'sp-sim', target: 'sp-battle', animated: true },
      { id: 'e-sp-model', source: 'sp-battle', target: 'sp-model', animated: true },
      { id: 'e-sp-insight', source: 'sp-model', target: 'sp-insight', animated: true },
    ],
  },
];

export const DIAGRAM_TABS: { id: FlowDiagramId; label: string }[] = [
  { id: 'inference', label: '문서 추론' },
  { id: 'onprem', label: '온프렘 구성' },
  { id: 'payment', label: '결제 적재' },
  { id: 'van', label: 'VAN 전환' },
  { id: 'point', label: '자사 포인트' },
  { id: 'kiosk', label: '다중 브랜드' },
  { id: 'stock', label: 'Stock Agent' },
  { id: 'spire', label: 'Spire 분석' },
];
